DEFOP(ASS, 1, "=")
DEFOP(ADD, 2, "+")
DEFOP(SUB, 3, "-")
DEFOP(MUL, 4, "*")
DEFOP(DIV, 5, "/")
DEFOP(POW, 6, "^")
DEFOP(MOR, 20, ">")
DEFOP(MOE, 21, ">=")
DEFOP(EQU, 22, "==")
DEFOP(NEQ, 23, "!=")
DEFOP(AND, 24, "and")

DEFFUNC(NUMBER, 7, "number")
DEFFUNC(SIN, 8, "sin")
DEFFUNC(COS, 9, "cos")
DEFFUNC(TAN, 10, "tan")
DEFFUNC(COT, 11, "cot")
DEFFUNC(LN, 12, "log")
DEFFUNC(SCANF, 13, "scanf")
DEFFUNC(PRINTF, 14, "printf")

DEFLOGIC(IF, 15, "if")
DEFLOGIC(ELS, 17, "else")
DEFLOGIC(WHI, 18, "while")
DEFLOGIC(FOR, 19, "for")


DEFKEYWORD(RET, 25, "return")
DEFKEYWORD(VAR, 26, "var")
DEFKEYWORD(MAI, 27, "main")
DEFKEYWORD(DEC, 28, "decl")
